version: '3.6'

volumes:
  grafana_config:

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=riverbed-appresponse-datasource
    ports:
      - '3000:3000'
    volumes:
      - grafana_config:/etc/grafana
      - ./grafana:/var/lib/grafana
