apiVersion: 1

datasources:
  - name: Riverbed AppResponse
    uid: riverbed-appresponse
    type: alidogan-appresponse-datasource
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      path: https://example.invalid
      username: demo
      tlsSkipVerify: true
